export class AirTicketRegModel  {

	public ID : number=0;
	public AirTicketTransCode : string;
	public TravelDate : string;
	public CustomerCode : string="0";
	public CompanyCode : string="0";
	public ArilineCode : string="0";
	public Route : string;
	public TicketNo : string;
	public SeatTypeCode : string="0";
	public TravelType : string="0";
	public TravelProvider : string="0";
	public ReturnDate : string;
	public CardID : string="0";
	public BaseFare : number=0;
	public GovTax : number=0;
	public ComissionAmount : number=0;
	public ServiceCharge : number=0;
	public ChangePenalty : number=0;
	public TotalPayable : number;
	public Currency : string="0";
	public CurrencyRate : number;
	public isConfirmed : boolean;
	public isCancel : boolean;
	public isForward : boolean;
	public ChangeDate : string;
	public Remarks : string;
	public SalesStaffCode : string="0";
	public CreatedBy : string;
	public CreatedOn : string;
	public UpdatedBy : string;
	public UpdatedOn : string;
	public isActive : boolean=true;
}